###  get-test
GET {{baseUrl}}/weblog/get-test?name=get-test
Content-Type: application/x-www-form-urlencoded

### name = get-test


###  post-test
POST {{baseUrl}}/weblog/post-test
Accept: application/json
Content-Type: application/json

{
   "name":"post-test"
}



### =================================演示登录================================================
### 演示POST请求
POST https://httpbin.org/post
Content-Type: application/json

{
  "user": "admin",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.json.token); %}
### 演示GET请求

GET https://httpbin.org/headers
Authorization: Bearer {{auth_token}}
### =================================================================================
